name: apn_cache
description: In memory caching service for Flutter projects
version: 1.0.1
homepage: https://github.com/appnormal/apn_cache

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.21.0
  lints: ^2.0.0
  equatable: ^2.0.3
  